on:
  workflow_dispatch:

env:
  WEBAPP_NAME: game-phaser3 # set this to your application's name
  WEBAPP_TARGET_PATH: "/root/web/game-phaser3" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "20.x" # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Copy files to VPS
        uses: cross-the-world/scp-pipeline@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          pass: ${{ secrets.SSH_PRIVATE_KEY }}
          local: "./dist"
          remote: ${{ env.WEBAPP_TARGET_PATH }}
